[package]
license = ["Apache-2.0"]
keywords = ["AI/OpenAI", "Cost/Paid", "image generation", "DALLE"]
org = "ballerinax"
name = "openai.images"
icon = "icon.png"
distribution = "2201.3.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.9.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
