[package]
license = ["Apache-2.0"]
keywords = ["AI/Images", "Cost/Paid", "image generation", "DALLE", "Vendor/OpenAI"]
org = "ballerinax"
name = "openai.images"
icon = "icon.png"
distribution = "2201.4.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
